use_frameworks!

target 'ReusableScrollMenuView_Example' do
  pod 'ReusableScrollMenuView', :path => '../'

  target 'ReusableScrollMenuView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
